all: optellen arrayPrint arrayMaximum rotateArray

optellen: optellen.cpp
		g++ -c optellen.cpp
		g++ -o optellen optellen.o
	

arrayPrint: arrayPrint.cpp
		g++ -c arrayPrint.cpp
		g++ -o arrayPrint arrayPrint.o

arrayMaximum: arrayMaximum.cpp
		g++ -c arrayMaximum.cpp
		g++ -o arrayMaximum arrayMaximum.o

rotateArray: rotateArray.cpp
		g++ -c rotateArray.cpp
		g++ -o rotateArray rotateArray.o
